# Project: Partizione_Memoria
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Crea_Partizione.o Alloca_Processo.o Stampa_Partizione.o
LINKOBJ  = main.o Crea_Partizione.o Alloca_Processo.o Stampa_Partizione.o
LIBS     = -L"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib" -L"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/include" -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/x86_64-w64-mingw32/include" -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/include" -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/x86_64-w64-mingw32/include" -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"Z:/home/alex/Downloads/DEEV/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Partizione_Memoria.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = Z:\home\alex\Downloads\DEEV\Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

Crea_Partizione.o: Crea_Partizione.c
	$(CC) -c Crea_Partizione.c -o Crea_Partizione.o $(CFLAGS)

Alloca_Processo.o: Alloca_Processo.c
	$(CC) -c Alloca_Processo.c -o Alloca_Processo.o $(CFLAGS)

Stampa_Partizione.o: Stampa_Partizione.c
	$(CC) -c Stampa_Partizione.c -o Stampa_Partizione.o $(CFLAGS)
